<?php

use App\Http\Controllers\CustomerPaymentPdfController;
use App\Http\Controllers\InvoicePdfController;
use App\Http\Controllers\QuotePdfController;
use App\Http\Controllers\SupplierPayablePdfController;
use App\Http\Controllers\SupplierPayablesSummaryPdfController;
use App\Http\Controllers\VendorBillPdfController;
use App\Http\Controllers\WhatsAppMediaController;
use App\Http\Controllers\AdminExportController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Auth\NewPasswordController;
use App\Http\Controllers\Auth\PasswordResetLinkController;
use App\Livewire\Admin\Dashboard;
use App\Livewire\Admin\Invoices\Index as InvoiceIndex;
use App\Livewire\Admin\Invoices\Show as InvoiceShow;
use App\Livewire\Admin\Invoices\RecordPayment;
use App\Livewire\Admin\Invoices\Create as InvoiceCreate;
use App\Livewire\Admin\Invoices\Edit as InvoiceEdit;
use App\Livewire\Admin\Leads\Create as LeadCreate;
use App\Livewire\Admin\Leads\Index as LeadIndex;
use App\Livewire\Admin\Leads\Show as LeadShow;
use App\Livewire\Admin\Leads\Pipeline as LeadPipeline;
use App\Livewire\Admin\Leads\DashboardIndex as LeadDashboardIndex;
use App\Livewire\Admin\Leads\Edit as LeadEdit;
use App\Livewire\Admin\Leads\OtherCreate;
use App\Livewire\Admin\Leads\OtherEdit;
use App\Livewire\Admin\Payments\Index as PaymentIndex;
use App\Livewire\Admin\Quotes\Create as QuoteCreate;
use App\Livewire\Admin\Quotes\Index as QuoteIndex;
use App\Livewire\Admin\Quotes\Show as QuoteShow;
use App\Livewire\Admin\Quotes\Edit as QuoteEdit;
use App\Livewire\Admin\Suppliers\Index as SupplierIndex;
use App\Livewire\Admin\VendorBills\Index as VendorBillIndex;
use App\Livewire\Admin\VendorBills\Create as VendorBillCreate;
use App\Livewire\Admin\VendorBills\Edit as VendorBillEdit;
use App\Livewire\Admin\SupplierPayments\Create as SupplierPaymentCreate;
use App\Livewire\Admin\Suppliers\Show as SupplierShow;
use App\Livewire\Admin\Suppliers\Create as SupplierCreate;
use App\Livewire\Admin\Suppliers\Edit as SupplierEdit;
use App\Livewire\Admin\VendorBills\Show as VendorBillShow;
use App\Livewire\Admin\Receivables\Index as ReceivableIndex;
use App\Livewire\Admin\Payments\CustomerShow as CustomerPaymentShow;
use App\Livewire\Admin\Payments\SupplierShow as SupplierPaymentShow;
use App\Livewire\Admin\Customers\Index as CustomerIndex;
use App\Livewire\Admin\Customers\Create as CustomerCreate;
use App\Livewire\Admin\Customers\Edit as CustomerEdit;
use App\Livewire\Admin\Customers\Show as CustomerShow;
use App\Livewire\Admin\Tours\Index as TourIndex;
use App\Livewire\Admin\Tours\Create as TourCreate;
use App\Livewire\Admin\Tours\Edit as TourEdit;
use App\Livewire\Admin\Tours\Show as TourShow;
use App\Livewire\Admin\TravelSchedule\Index as TravelScheduleIndex;
use App\Livewire\Admin\CallCentre\Index as CallCentreIndex;
use App\Livewire\Admin\CallCentre\Show as CallCentreShow;
use App\Livewire\Admin\WhatsApp\Index as WhatsAppIndex;
use App\Livewire\Admin\WhatsApp\Show as WhatsAppShow;
use App\Livewire\Admin\Leave\Index as LeaveIndex;
use App\Livewire\Admin\Leave\Create as LeaveCreate;
use App\Livewire\Admin\Leave\Show as LeaveShow;
use App\Livewire\Admin\Leave\Calendar as LeaveCalendar;
use App\Livewire\Admin\Closures\Index as ClosureIndex;
use App\Livewire\Admin\Users\Index as UserIndex;
use App\Livewire\Admin\Users\Create as UserCreate;
use App\Livewire\Admin\Users\Edit as UserEdit;
use App\Livewire\Admin\Access\Groups as PermissionGroups;
use App\Livewire\Admin\Analytics\Index as AnalyticsIndex;
use App\Livewire\Admin\Analytics\Staff as AnalyticsStaff;
use App\Livewire\Admin\Notifications\Index as NotificationIndex;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect()->route(auth()->check() ? 'admin.dashboard' : 'admin.login');
});

Route::middleware('guest')->prefix('admin')->name('admin.')->group(function (): void {
    Route::get('/login', [AuthenticatedSessionController::class, 'create'])->name('login');
    Route::post('/login', [AuthenticatedSessionController::class, 'store'])->name('login.store');
    Route::get('/forgot-password', [PasswordResetLinkController::class, 'create'])->name('password.request');
    Route::post('/forgot-password', [PasswordResetLinkController::class, 'store'])->name('password.email');
    Route::get('/reset-password/{token}', [NewPasswordController::class, 'create'])->name('password.reset');
    Route::post('/reset-password', [NewPasswordController::class, 'store'])->name('password.update');
});

Route::middleware('auth')->prefix('admin')->name('admin.')->group(function (): void {
    Route::get('/', Dashboard::class)->name('dashboard');
    Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');
    Route::get('/leads', LeadIndex::class)->name('leads.index');
    Route::get('/sales-pipeline', LeadPipeline::class)->name('leads.pipeline');
    Route::get('/other-leads', LeadDashboardIndex::class)->defaults('mode', 'other')->name('dashboard.other');
    Route::get('/other-leads/create', OtherCreate::class)->name('other-leads.create');
    Route::get('/other-leads/{lead}/edit', OtherEdit::class)->name('other-leads.edit');
    Route::get('/my-sales', LeadDashboardIndex::class)->defaults('mode', 'my-sales')->name('dashboard.my-sales');
    Route::get('/cruise-leads', LeadDashboardIndex::class)->defaults('mode', 'cruise')->name('dashboard.cruise');
    Route::get('/group-leads', LeadDashboardIndex::class)->defaults('mode', 'group')->name('dashboard.group');
    Route::get('/confirmed-leads', LeadDashboardIndex::class)->defaults('mode', 'confirmed')->name('dashboard.confirmed');
    Route::get('/document-complete-leads', LeadDashboardIndex::class)->defaults('mode', 'documents')->name('dashboard.documents');
    Route::get('/my-operation-leads', LeadDashboardIndex::class)->defaults('mode', 'operations')->name('dashboard.operations');
    Route::get('/my-call-centre-leads', LeadDashboardIndex::class)->defaults('mode', 'call-centre')->name('dashboard.call-centre');
    Route::get('/archived-leads', LeadDashboardIndex::class)->defaults('mode', 'archived')->name('dashboard.archived');
    Route::get('/visa-leads', LeadDashboardIndex::class)->defaults('mode', 'visa')->name('dashboard.visa');
    Route::get('/internal-notes', LeadDashboardIndex::class)->defaults('mode', 'notes')->name('dashboard.notes');
    Route::get('/leads/create', LeadCreate::class)->name('leads.create');
    Route::get('/leads/{lead}', LeadShow::class)->name('leads.show');
    Route::get('/leads/{lead}/edit', LeadEdit::class)->name('leads.edit');
    Route::get('/quotes', QuoteIndex::class)->name('quotes.index');
    Route::get('/quotes/create', QuoteCreate::class)->name('quotes.create');
    Route::get('/quotes/{quote}/edit', QuoteEdit::class)->name('quotes.edit');
    Route::get('/quotes/{quote}', QuoteShow::class)->name('quotes.show');
    Route::get('/invoices', InvoiceIndex::class)->name('invoices.index');
    Route::get('/invoices/create', InvoiceCreate::class)->name('invoices.create');
    Route::get('/invoices/{invoice}/edit', InvoiceEdit::class)->name('invoices.edit');
    Route::get('/invoices/{invoice}/payments/create', RecordPayment::class)->name('invoices.payments.create');
    Route::get('/invoices/{invoice}', InvoiceShow::class)->name('invoices.show');
    Route::get('/suppliers', SupplierIndex::class)->name('suppliers.index');
    Route::get('/suppliers/create', SupplierCreate::class)->name('suppliers.create');
    Route::get('/suppliers/{supplier}/edit', SupplierEdit::class)->name('suppliers.edit');
    Route::get('/suppliers/{supplier}', SupplierShow::class)->name('suppliers.show');
    Route::get('/vendor-bills', VendorBillIndex::class)->name('vendor-bills.index');
    Route::get('/vendor-bills/create', VendorBillCreate::class)->name('vendor-bills.create');
    Route::get('/vendor-bills/{vendorBill}/edit', VendorBillEdit::class)->name('vendor-bills.edit');
    Route::get('/vendor-bills/{vendorBill}', VendorBillShow::class)->name('vendor-bills.show');
    Route::get('/supplier-payments/create', SupplierPaymentCreate::class)->name('supplier-payments.create');
    Route::get('/receivables', ReceivableIndex::class)->name('receivables.index');
    Route::get('/payments/customer/{customerPayment}', CustomerPaymentShow::class)->name('payments.customer.show');
    Route::get('/payments/supplier/{supplierPayment}', SupplierPaymentShow::class)->name('payments.supplier.show');
    Route::get('/customers', CustomerIndex::class)->name('customers.index');
    Route::get('/customers/create', CustomerCreate::class)->name('customers.create');
    Route::get('/customers/{customer}/edit', CustomerEdit::class)->name('customers.edit');
    Route::get('/customers/{customer}', CustomerShow::class)->name('customers.show');
    Route::get('/tours', TourIndex::class)->name('tours.index');
    Route::get('/tours/create', TourCreate::class)->name('tours.create');
    Route::get('/tours/{tour}/edit', TourEdit::class)->name('tours.edit');
    Route::get('/tours/{tour}', TourShow::class)->name('tours.show');
    Route::get('/arrivals', TravelScheduleIndex::class)->defaults('mode','arrivals')->name('arrivals.index');
    Route::get('/departures', TravelScheduleIndex::class)->defaults('mode','departures')->name('departures.index');
    Route::get('/calls', CallCentreIndex::class)->name('calls.index');
    Route::get('/calls/{call}', CallCentreShow::class)->name('calls.show');
    Route::get('/whatsapp', WhatsAppIndex::class)->name('whatsapp.index');
    Route::get('/whatsapp/{conversation}', WhatsAppShow::class)->name('whatsapp.show');
    Route::get('/leave', LeaveIndex::class)->name('leave.index');
    Route::get('/leave/create', LeaveCreate::class)->name('leave.create');
    Route::get('/leave/calendar', LeaveCalendar::class)->name('leave.calendar');
    Route::get('/leave/{leave}', LeaveShow::class)->name('leave.show');
    Route::get('/office-closures', ClosureIndex::class)->name('closures.index');
    Route::get('/users', UserIndex::class)->name('users.index');
    Route::get('/users/create', UserCreate::class)->name('users.create');
    Route::get('/users/{user}/edit', UserEdit::class)->name('users.edit');
    Route::get('/permission-groups', PermissionGroups::class)->name('permission-groups.index');
    Route::get('/analytics', AnalyticsIndex::class)->name('analytics.index');
    Route::get('/analytics/staff', AnalyticsStaff::class)->name('analytics.staff');
    Route::get('/exports/{type}', AdminExportController::class)->whereIn('type',['leads','invoices','staff'])->name('exports.download');
    Route::get('/payments', PaymentIndex::class)->name('payments.index');
    Route::get('/notifications', NotificationIndex::class)->name('notifications');
});

Route::middleware(['web', 'auth'])->group(function () {
    Route::get('/finance/invoices/{invoice}/pdf', InvoicePdfController::class)->name('finance.invoices.pdf');
    Route::get('/finance/quotes/{quote}/pdf', QuotePdfController::class)->name('finance.quotes.pdf');
    Route::get('/finance/vendor-bills/{vendorBill}/pdf', VendorBillPdfController::class)->name('finance.vendor-bills.pdf');
    Route::get('/finance/customer-payments/{customerPayment}/pdf', CustomerPaymentPdfController::class)->name('finance.customer-payments.pdf');
    Route::get('/finance/supplier-payables/pdf', SupplierPayablesSummaryPdfController::class)->name('finance.supplier-payables.summary-pdf');
    Route::get('/finance/supplier-payables/{supplier}/pdf', SupplierPayablePdfController::class)->name('finance.supplier-payables.pdf');
    Route::get('/admin/whatsapp-media/{message}', [WhatsAppMediaController::class, 'show'])->name('whatsapp.media');
});
