<?php
namespace App\Livewire\Admin\Invoices;
use App\Models\Invoice; use App\Models\Lead; use App\Services\DocumentNumberService; use Illuminate\Support\Facades\DB; use Illuminate\Validation\ValidationException; use Livewire\Component;
class Create extends Component
{
 public ?int $lead_id=null;public string $invoice_date='';public string $due_date='';public string $terms='Due on Receipt';public string $subject='';public string $description='';public string $notes='';public array $lines=[['description'=>'','customer_details'=>'','quantity'=>1,'rate'=>0]];
 public function mount():void{$u=auth()->user();abort_unless($u->canManageAccountingRecords()||$u->isSales()||$u->isOperation()||$u->canCreateResource('invoices'),403);$this->invoice_date=now()->toDateString();$this->due_date=now()->toDateString();$this->lead_id=request()->integer('lead')?:null;}
 public function addLine():void{$this->lines[]=['description'=>'','customer_details'=>'','quantity'=>1,'rate'=>0];}public function removeLine(int $i):void{if(count($this->lines)>1){unset($this->lines[$i]);$this->lines=array_values($this->lines);}}
 public function save(DocumentNumberService $numbers){$data=$this->validate($this->rules());$user=auth()->user();$lead=Lead::findOrFail($data['lead_id']);if(!$user->canViewAllInvoices()&&($user->isSales()||$user->isOperation())&&!$user->hasLeadAssigned($lead))throw ValidationException::withMessages(['lead_id'=>'You can only create invoices for leads assigned to you.']);$invoice=DB::transaction(function()use($data,$numbers){$lines=$data['lines'];unset($data['lines']);$data['invoice_number']=$numbers->nextInvoiceNumberForLead($data['lead_id']);$data['total_amount']=0;$invoice=Invoice::create($data);$invoice->replaceLineItemsFromFormState($lines);$invoice->recalculateTotalsFromLineItems();return $invoice;});session()->flash('success','Invoice created.');return $this->redirectRoute('admin.invoices.show',$invoice,navigate:true);}
 private function rules():array{return ['lead_id'=>['required','exists:leads,id'],'invoice_date'=>['required','date'],'due_date'=>['required','date','after_or_equal:invoice_date'],'terms'=>['nullable','string','max:255'],'subject'=>['nullable','string','max:255'],'description'=>['nullable','string','max:5000'],'notes'=>['nullable','string','max:5000'],'lines'=>['required','array','min:1'],'lines.*.description'=>['required','string','max:2000'],'lines.*.customer_details'=>['nullable','string','max:255'],'lines.*.quantity'=>['required','numeric','gt:0'],'lines.*.rate'=>['required','numeric','min:0']];}
 public function render(){return view('livewire.admin.invoices.form',['heading'=>'New invoice','submitLabel'=>'Create invoice','leads'=>Lead::query()->forFinanceLeadSelection(auth()->user())->where('is_other_lead',false)->latest()->limit(250)->get(),'creating'=>true])->layout('components.layouts.admin',['title'=>'New invoice']);}
}
