<?php
namespace App\Livewire\Admin\Invoices;
use App\Models\Invoice; use Illuminate\Support\Facades\DB; use Illuminate\Validation\ValidationException; use Livewire\Component;
class Edit extends Component
{
 public Invoice $invoice;public ?int $lead_id=null;public string $invoice_date='';public string $due_date='';public string $terms='';public string $subject='';public string $description='';public string $notes='';public array $lines=[];
 public function mount():void{abort_unless(auth()->user()->canEditInvoices(),403);$this->invoice->load(['lineItems','customerPayments']);foreach(['lead_id','terms','subject','description','notes'] as $f)$this->$f=$this->invoice->$f??'';$this->invoice_date=$this->invoice->invoice_date?->toDateString()??now()->toDateString();$this->due_date=$this->invoice->due_date?->toDateString()??now()->toDateString();$this->lines=$this->invoice->lineItems->map(fn($l)=>['description'=>$l->description,'customer_details'=>$l->customer_details,'quantity'=>$l->quantity,'rate'=>$l->rate])->values()->all();if($this->lines===[])$this->lines=[['description'=>'','customer_details'=>'','quantity'=>1,'rate'=>0]];}
 public function addLine():void{$this->lines[]=['description'=>'','customer_details'=>'','quantity'=>1,'rate'=>0];}public function removeLine(int $i):void{if(count($this->lines)>1){unset($this->lines[$i]);$this->lines=array_values($this->lines);}}
 public function save(){$data=$this->validate(['invoice_date'=>['required','date'],'due_date'=>['required','date','after_or_equal:invoice_date'],'terms'=>['nullable','string','max:255'],'subject'=>['nullable','string','max:255'],'description'=>['nullable','string','max:5000'],'notes'=>['nullable','string','max:5000'],'lines'=>['required','array','min:1'],'lines.*.description'=>['required','string','max:2000'],'lines.*.customer_details'=>['nullable','string','max:255'],'lines.*.quantity'=>['required','numeric','gt:0'],'lines.*.rate'=>['required','numeric','min:0']]);DB::transaction(function()use($data){$invoice=Invoice::query()->lockForUpdate()->findOrFail($this->invoice->id);$total=round(collect($data['lines'])->sum(fn($l)=>(float)$l['quantity']*(float)$l['rate']),2);$paid=round((float)$invoice->customerPayments()->sum('amount'),2);if($total+0.0001<$paid)throw ValidationException::withMessages(['lines'=>'Invoice total cannot be below the amount already received: LKR '.number_format($paid,2).'.']);$lines=$data['lines'];unset($data['lines']);$invoice->update($data);$invoice->replaceLineItemsFromFormState($lines);$invoice->recalculateTotalsFromLineItems();});session()->flash('success','Invoice updated.');return $this->redirectRoute('admin.invoices.show',$this->invoice,navigate:true);}
 public function render(){return view('livewire.admin.invoices.form',['heading'=>'Edit '.$this->invoice->invoice_number,'submitLabel'=>'Save changes','leads'=>collect([$this->invoice->lead]),'creating'=>false])->layout('components.layouts.admin',['title'=>'Edit '.$this->invoice->invoice_number]);}
}
