<?php

return [
    'required_routes' => [
        'admin.dashboard', 'admin.leads.index', 'admin.leads.show', 'admin.leads.pipeline',
        'admin.dashboard.archived', 'admin.dashboard.documents', 'admin.dashboard.operations',
        'admin.dashboard.call-centre', 'admin.quotes.index', 'admin.invoices.index',
        'admin.receivables.index', 'admin.vendor-bills.index', 'admin.suppliers.index',
        'admin.payments.index', 'admin.customers.index', 'admin.tours.index',
        'admin.arrivals.index', 'admin.departures.index', 'admin.calls.index',
        'admin.whatsapp.index', 'admin.leave.index', 'admin.leave.calendar',
        'admin.closures.index', 'admin.users.index', 'admin.permission-groups.index',
        'admin.analytics.index', 'admin.analytics.staff',
    ],

    // Each legacy capability is represented by the native routes that replace it.
    'capabilities' => [
        'Main dashboard' => ['admin.dashboard'],
        'All lead workspace' => ['admin.leads.index', 'admin.leads.create', 'admin.leads.show', 'admin.leads.edit'],
        'Sales pipeline' => ['admin.leads.pipeline'],
        'My sales leads' => ['admin.dashboard.my-sales'],
        'Operations leads' => ['admin.dashboard.operations'],
        'Call-centre leads' => ['admin.dashboard.call-centre', 'admin.leads.create'],
        'Other leads' => ['admin.dashboard.other', 'admin.other-leads.create', 'admin.other-leads.edit'],
        'Cruise leads' => ['admin.dashboard.cruise'],
        'Group leads' => ['admin.dashboard.group'],
        'Confirmed leads' => ['admin.dashboard.confirmed'],
        'Document-complete leads' => ['admin.dashboard.documents'],
        'Archived leads' => ['admin.dashboard.archived'],
        'Internal notes' => ['admin.dashboard.notes'],
        'Quotes' => ['admin.quotes.index', 'admin.quotes.create', 'admin.quotes.show', 'admin.quotes.edit'],
        'Invoices' => ['admin.invoices.index', 'admin.invoices.create', 'admin.invoices.show', 'admin.invoices.edit'],
        'Customer receivables' => ['admin.receivables.index', 'admin.invoices.payments.create'],
        'Vendor bills' => ['admin.vendor-bills.index', 'admin.vendor-bills.create', 'admin.vendor-bills.show', 'admin.vendor-bills.edit'],
        'Supplier payables and payments' => ['admin.suppliers.index', 'admin.supplier-payments.create', 'admin.payments.supplier.show'],
        'Payment register' => ['admin.payments.index'],
        'Customers' => ['admin.customers.index', 'admin.customers.create', 'admin.customers.show', 'admin.customers.edit'],
        'Tours and tour finance' => ['admin.tours.index', 'admin.tours.create', 'admin.tours.show', 'admin.tours.edit'],
        'Arrivals' => ['admin.arrivals.index'],
        'Departures' => ['admin.departures.index'],
        'Call-centre calls' => ['admin.calls.index', 'admin.calls.show'],
        'WhatsApp inbox and my chats' => ['admin.whatsapp.index', 'admin.whatsapp.show'],
        'Leave requests and leave management' => ['admin.leave.index', 'admin.leave.create', 'admin.leave.show', 'admin.leave.calendar'],
        'Office closures' => ['admin.closures.index'],
        'Users and team members' => ['admin.users.index', 'admin.users.create', 'admin.users.edit'],
        'Permissions' => ['admin.permission-groups.index'],
        'Analytics dashboard' => ['admin.analytics.index'],
        'Sales staff performance' => ['admin.analytics.staff'],
        'Exports' => ['admin.exports.download'],
    ],
];
